[package]
name = "tankersdk-android"
version = "0.1.0"
authors = ["Yan Bonnel <yan.bonnel@doctolib.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tankersdk = { version = "2.16.1-beta1", registry = "tanker" }
